blank_issues_enabled: false
contact_links:
  - name: WeKnora Documentation
    url: https://weknora.weixin.qq.com/docs/01-getting-started/05-troubleshooting
    about: Check WeKnora FAQ
  - name: Discussions
    url: https://github.com/Tencent/WeKnora/discussions
    about: Ask questions or share ideas in Discussions
