DROP TABLE IF EXISTS memory_item_embeddings;
DROP INDEX IF EXISTS idx_mem_affinity_scope;
DROP TABLE IF EXISTS memory_doc_affinity;
DROP INDEX IF EXISTS idx_mem_topic_scope;
DROP TABLE IF EXISTS memory_topic_stats;
DROP INDEX IF EXISTS idx_memory_items_key;
DROP INDEX IF EXISTS idx_memory_items_scope;
DROP TABLE IF EXISTS memory_items;
DROP INDEX IF EXISTS idx_mem_tomb_fp;
DROP INDEX IF EXISTS idx_memory_tombstones_scope;
DROP TABLE IF EXISTS memory_tombstones;
DROP INDEX IF EXISTS idx_memory_subjects_scope;
DROP TABLE IF EXISTS memory_subjects;
ALTER TABLE tenants DROP COLUMN IF EXISTS memory_config;
ALTER TABLE messages DROP COLUMN IF EXISTS used_memories;
