// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AutoCheckForUpdates():Promise<void>;

export function CheckForUpdates():Promise<void>;

export function GetAPIBaseURL():Promise<string>;

export function GetAPILanBaseURL():Promise<string>;

export function GetDesktopHTTPBindPublicSetting():Promise<boolean>;

export function GetDesktopHTTPPortSetting():Promise<number>;

export function GetDesktopListenPublicActive():Promise<boolean>;

export function SetDesktopHTTPBindPublicSetting(arg1:boolean):Promise<void>;

export function SetDesktopHTTPPortSetting(arg1:number):Promise<void>;
